Repository wrf-model/WPS, pull requests merged in 2021-05, with the labels that each got.

#165 Fix URL for getting NARR static grib1 data
  ungrib/Variable_Tables/Vtable.NARR
Labels: Desired for v4.3

#166 Noahmp dyamic irrigation
  geogrid/GEOGRID.TBL.ARW.noahmp
Labels: Required for v4.3

#172 Update GEOGRID tables for NoahMP, fire and chem
  geogrid/GEOGRID.TBL.ARW.noahmp
  geogrid/GEOGRID.TBL.ARW_CHEM
  geogrid/GEOGRID.TBL.FIRE
Labels: Desired for v4.3

#171 Add 20 new gwd fields
  geogrid/GEOGRID.TBL.ARW
Labels: Required for v4.3

#156 Update "build_hdate.F" for 3-digit years
  ungrib/src/build_hdate.F
Labels: Desired for v4.3, enhancement, ungrib

#157 Update "geth_newdate.F" for 3-digit years
  ungrib/src/geth_newdate.F
Labels: Desired for v4.3, enhancement, ungrib

#160 namelist.wps updates to newer case dates/domain to match updated default namelist.input
  namelist.wps
Labels: Required for v4.3

#158 GEFS sep2020 landmask fix
  ungrib/src/rrpr.F
Labels: Required for v4.3

#175 Add --nowrf option to configure script, for configuring without WRF
  configure
Labels: Desired for v4.3

#176 Fix default input data resolution for gwd field ol3ss
  geogrid/GEOGRID.TBL.ARW
Labels: Required for v4.3, bug

#177 Add new GWD fields to NoahMP, Chem, and Fire GEOGRID.TBL files
  geogrid/GEOGRID.TBL.ARW.noahmp
  geogrid/GEOGRID.TBL.ARW_CHEM
  geogrid/GEOGRID.TBL.FIRE
Labels: Required for v4.3

#178 Updated namelist.wps for consistency with updates to namelist.input
  namelist.wps
Labels: Required for v4.3, cleanup
